# Generated by Django 5.2.5 on 2025-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_options_doctor_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
